language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.6
      env: PTR_INTEGRATION=1
    - python: 3.7
    - python: 3.7
      env: PTR_INTEGRATION=1
    - python: 3.8-dev
  allow_failures:
    - python: 3.5
    - python: 3.8-dev

script:
    - python ci.py

notifications:
  irc:
    channels:
      - "chat.freenode.net#pythontestrunner"

cache:
    directories:
        - $HOME/.cache/pip
